export enum CustomApiError {
  EMAIL_REGISTERED = 'EMAIL_REGISTERED',
  INVALID_AUTH_TOKEN = 'INVALID_AUTH_TOKEN',
  EXPIRED_AUTH_TOKEN = 'EXPIRED_AUTH_TOKEN',
  INVALID_LOGIN_CODE = 'INVALID_LOGIN_CODE',
  EXPIRED_LOGIN_CODE = 'EXPIRED_LOGIN_CODE',
  UNABLE_TO_SEND = 'UNABLE_TO_SEND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
}

export enum CustomValidationError {
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_LOGIN_CODE = 'INVALID_LOGIN_CODE',
  STRING_REQUIRED = 'STRING_REQUIRED',
  NUMBER_REQUIRED = 'NUMBER_REQUIRED',
  ARRAY_REQUIRED = 'ARRAY_REQUIRED',
  BOOLEAN_REQUIRED = 'BOOLEAN_REQUIRED',
  TEXT_OR_LINK_REQUIRED = 'TEXT_OR_LINK_REQUIRED',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  MIN_VALUE = 'MIN_VALUE',
  MAX_VALUE = 'MAX_VALUE',
  INVALID_DATE = 'INVALID_DATE',
  INVALID_URL = 'INVALID_URL',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
  INVALID_UUID = 'INVALID_UUID',
  INVALID_LINK = 'INVALID_LINK',
}
